# Generated by Django 2.1.5 on 2019-09-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='area',
            field=models.TextField(default=1, verbose_name='Working Area'),
            preserve_default=False,
        ),
    ]
