# Generated by Django 2.1.5 on 2019-09-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Charge',
            field=models.TextField(default=1, verbose_name='Charges'),
            preserve_default=False,
        ),
    ]
