# Generated by Django 2.1.5 on 2019-09-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Charge',
            field=models.CharField(max_length=10, verbose_name='Charges'),
        ),
    ]
