# Generated by Django 2.2.1 on 2019-09-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190914_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Contact info')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
