# Generated by Django 2.2.1 on 2019-09-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_abouttitle_contacttitle_portfoliotitle_servicetitle_testimonialtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='adressTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Enter Address bar Title')),
            ],
        ),
        migrations.AlterField(
            model_name='abouttitle',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Enter About Title'),
        ),
        migrations.AlterField(
            model_name='portfoliotitle',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Enter Portfolio Title'),
        ),
        migrations.AlterField(
            model_name='servicetitle',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Enter Service Title'),
        ),
        migrations.AlterField(
            model_name='testimonialtitle',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Enter Testimonial Title'),
        ),
    ]
