# Generated by Django 2.2.1 on 2019-09-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190919_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Add Footer Text')),
            ],
        ),
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Images name')),
                ('image1', models.ImageField(upload_to='Slide Image 1')),
                ('image2', models.ImageField(upload_to='Slide Image 1')),
                ('image3', models.ImageField(upload_to='Slide Image 1')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(verbose_name='Contact/Address info'),
        ),
    ]
