# Generated by Django 2.2.1 on 2019-09-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190920_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideimage',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='slideimage',
            name='image3',
        ),
        migrations.AddField(
            model_name='slideimage',
            name='descreption',
            field=models.CharField(default=1, max_length=100, verbose_name='Images Descreption'),
            preserve_default=False,
        ),
    ]
