# Generated by Django 2.2.1 on 2019-09-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190920_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideimage',
            name='descreption',
        ),
        migrations.RemoveField(
            model_name='slideimage',
            name='image1',
        ),
        migrations.AddField(
            model_name='slideimage',
            name='description',
            field=models.CharField(default=1, max_length=100, verbose_name='Images Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slideimage',
            name='image',
            field=models.ImageField(default=1, upload_to='Slide Image '),
            preserve_default=False,
        ),
    ]
