# Generated by Django 3.0a1 on 2019-09-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofileinfo_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='msg',
            new_name='status',
        ),
    ]
