# Generated by Django 3.0a1 on 2019-09-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190928_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='d_date',
            field=models.CharField(default=1, max_length=100, verbose_name='Estimated Completion Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='job',
            field=models.CharField(default=1, max_length=100, verbose_name='Service Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='o_date',
            field=models.CharField(default=1, max_length=100, verbose_name='Date of Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Current Status'),
        ),
    ]
