# Generated by Django 2.2.6 on 2019-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='update_at',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
