# Generated by Django 2.2.7 on 2019-11-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20191120_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Debug_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Developing_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Piloting_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Ready_at',
            field=models.TextField(blank=True, null=True),
        ),
    ]
